version: 0.2

phases:
  pre_build:
    commands:
      - start-dockerd

  build:
    commands:
      # run linters
      - TOX_PARALLEL_NO_SPINNER=1
      - tox -e flake8,black-check,pylint --parallel all

      # run README check
      - tox -e twine

      # run unit tests
      - AWS_ACCESS_KEY_ID= AWS_SECRET_ACCESS_KEY= AWS_SESSION_TOKEN=
        AWS_CONTAINER_CREDENTIALS_RELATIVE_URI= AWS_DEFAULT_REGION=
        tox -v -e py37,py38 --parallel all -- test/unit

      # build toolkit
      - python setup.py sdist

      # build a SageMaker Training Compiler container with AWS PT-XLA
      - aws ecr get-login-password --region ${AWS_REGION} | 
        docker login --username AWS --password-stdin 763104351884.dkr.ecr.${AWS_REGION}.amazonaws.com
      - cp dist/sagemaker_training-*.tar.gz test/container/trcomp_pytorch/sagemaker_training.tar.gz
      - docker build -t sagemaker-training-toolkit-test:trcomp_pytorch -f test/container/trcomp_pytorch/Dockerfile . 
        --build-arg AWS_REGION
      - rm test/container/trcomp_pytorch/sagemaker_training.tar.gz

      # build a mock container with OSS PT-XLA
      - cp dist/sagemaker_training-*.tar.gz test/container/oss_pt_xla/sagemaker_training.tar.gz
      - docker build -t sagemaker-training-toolkit-test:oss_pt_xla -f test/container/oss_pt_xla/Dockerfile . 
        --build-arg AWS_REGION
      - rm test/container/oss_pt_xla/sagemaker_training.tar.gz

      # run unit tests in SageMaker Training Compiler container
      - docker run sagemaker-training-toolkit-test:trcomp_pytorch 
        -e AWS_ACCESS_KEY_ID='' -e AWS_SECRET_ACCESS_KEY='' -e AWS_SESSION_TOKEN=''
        -e AWS_CONTAINER_CREDENTIALS_RELATIVE_URI='' -e AWS_DEFAULT_REGION=''
        tox -v -e py37,py38 --parallel all -- test/unit

      # run unit tests in OSS PT-XLA container
      - docker run sagemaker-training-toolkit-test:oss_pt_xla 
        -e AWS_ACCESS_KEY_ID='' -e AWS_SECRET_ACCESS_KEY='' -e AWS_SESSION_TOKEN=''
        -e AWS_CONTAINER_CREDENTIALS_RELATIVE_URI='' -e AWS_DEFAULT_REGION=''
        tox -v -e py37,py38 --parallel all -- test/unit

      # run functional tests
      - $(aws ecr get-login --no-include-email --region us-west-2)
      - IGNORE_COVERAGE=- tox -v -e py37,py38 -- test/functional

      # build dummy container
      - cp dist/sagemaker_training-*.tar.gz test/container/dummy/sagemaker_training.tar.gz
      - cd test/container
      - docker build -t sagemaker-training-toolkit-test:dummy -f dummy/Dockerfile .
      - rm dummy/sagemaker_training.tar.gz

      - cd ../..

      # run local integration tests
      - IGNORE_COVERAGE=- tox -v -e py37,py38 -- test/integration/local
